### ISSUE TITLE
sortByRegionCount - function already defined

### ISSUE THREAD

**Issue by frega** [drupal-fancy/view_mode_selector#3]
In some circumstances (e.g. if view_mode_selector_field_widget_form is called multiple times) the function 'sortByRegionCount' is already defined and causes a fatal errors view_mode_selector_field_widget_form.module:188ff. 

Let's wrap it in a function exists call

```
if (!function_exists('sortByRegionCount')) {
  // Sort Display Suite view modes by number of regions.
  function sortByRegionCount($a, $b) {
    return count($a['layout']['settings']['regions']) - count($b['layout']['settings']['regions']);
  }
}
```

**Comment by axe312ger** [comment]
This is already fixed in this commit: https://github.com/drupal-fancy/view_mode_selector/commit/d0acaeec8079e62e2f78d8f35efe45eef18e051a

We will tag a new release soon :)

**Comment by fmuellerprevion** [comment]
Because the stable version on the Drupal Project page is still not having the commit, you may use the attached patch file to apply the exact commited changes to your module until the dev version gets into stable .(Rename the file from .txt to .patch and apply it using PhpStorm or whatever you're using).

[sortByRegionCount_function_already_defined.txt](https://github.com/drupal-fancy/view_mode_selector/files/2197807/sortByRegionCount_function_already_defined.txt)
